In [2]:
%matplotlib inline

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression, Perceptron, SGDClassifier
from sklearn.svm import LinearSVR
from sklearn.ensemble import VotingClassifier, StackingClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.datasets import load_digits

# Introduction to Neural Networks - NN

Имплементации на алгоритми за Recommendation systems може да се видят на: 
    - https://surpriselib.com/
    
Check this libraries:

    - yellowbrick: https://www.scikit-yb.org/en/latest/
    - dask: https://www.dask.org/
    - https://imbalanced-learn.org/stable/
    - https://dvc.org/
    - https://github.com/hyperopt/hyperopt-sklearn
    - https://scipy.org/

Machine learning Комикси:
- https://xkcd.com/1838/

In [5]:
log_regr = LogisticRegression()

In [6]:
log_regr = [LogisticRegression() for _ in range(20)]

In [7]:
log_regr

[LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression(),
 LogisticRegression()]

In [22]:
log_regrs = [(f"log_regr_{i}", LogisticRegression()) for i in range(20)]

In [23]:
voting = VotingClassifier(log_regrs)

In [24]:
voting

VotingClassifier(estimators=[('log_regr_0', LogisticRegression()),
                             ('log_regr_1', LogisticRegression()),
                             ('log_regr_2', LogisticRegression()),
                             ('log_regr_3', LogisticRegression()),
                             ('log_regr_4', LogisticRegression()),
                             ('log_regr_5', LogisticRegression()),
                             ('log_regr_6', LogisticRegression()),
                             ('log_regr_7', LogisticRegression()),
                             ('log_regr_8', LogisticRegression(...
                             ('log_regr_10', LogisticRegression()),
                             ('log_regr_11', LogisticRegression()),
                             ('log_regr_12', LogisticRegression()),
                             ('log_regr_13', LogisticRegression()),
                             ('log_regr_14', LogisticRegression()),
                             ('log_regr_15', LogisticRegression()),
                             ('log_regr_16', LogisticRegression()),
                             ('log_regr_17', LogisticRegression()),
                             ('log_regr_18', LogisticRegression()),
                             ('log_regr_19', LogisticRegression())])

In [26]:
voting_classifiers = [(f"voting_{i}", VotingClassifier(log_regrs)) for i in range(5)]  # layer

In [27]:
StackingClassifier(voting_classifiers)  # this is one neural network

StackingClassifier(estimators=[('voting_0',
                                VotingClassifier(estimators=[('log_regr_0',
                                                              LogisticRegression()),
                                                             ('log_regr_1',
                                                              LogisticRegression()),
                                                             ('log_regr_2',
                                                              LogisticRegression()),
                                                             ('log_regr_3',
                                                              LogisticRegression()),
                                                             ('log_regr_4',
                                                              LogisticRegression()),
                                                             ('log_regr_5',
                                                              LogisticRegression()),
                                                             ('log_regr_6',
                                                              LogisticRegression()),
                                                             ('log_regr_7',
                                                              LogisticRegr...
                                                              LogisticRegression()),
                                                             ('log_regr_11',
                                                              LogisticRegression()),
                                                             ('log_regr_12',
                                                              LogisticRegression()),
                                                             ('log_regr_13',
                                                              LogisticRegression()),
                                                             ('log_regr_14',
                                                              LogisticRegression()),
                                                             ('log_regr_15',
                                                              LogisticRegression()),
                                                             ('log_regr_16',
                                                              LogisticRegression()),
                                                             ('log_regr_17',
                                                              LogisticRegression()),
                                                             ('log_regr_18',
                                                              LogisticRegression()),
                                                             ('log_regr_19',
                                                              LogisticRegression())]))])

Стак от слоеве можем да наречен невронна мрежа. Тези слоеве работят защото са ансамбли.

In [30]:
sgd = SGDClassifier(loss = "hinge")

In [33]:
units = [(f"unit_{i}", SGDClassifier(loss = "hinge")) for i in range(20)]

In [34]:
units

[('unit_0', SGDClassifier()),
 ('unit_1', SGDClassifier()),
 ('unit_2', SGDClassifier()),
 ('unit_3', SGDClassifier()),
 ('unit_4', SGDClassifier()),
 ('unit_5', SGDClassifier()),
 ('unit_6', SGDClassifier()),
 ('unit_7', SGDClassifier()),
 ('unit_8', SGDClassifier()),
 ('unit_9', SGDClassifier()),
 ('unit_10', SGDClassifier()),
 ('unit_11', SGDClassifier()),
 ('unit_12', SGDClassifier()),
 ('unit_13', SGDClassifier()),
 ('unit_14', SGDClassifier()),
 ('unit_15', SGDClassifier()),
 ('unit_16', SGDClassifier()),
 ('unit_17', SGDClassifier()),
 ('unit_18', SGDClassifier()),
 ('unit_19', SGDClassifier())]

In [35]:
layer = VotingClassifier(units)

In [36]:
layer

VotingClassifier(estimators=[('unit_0', SGDClassifier()),
                             ('unit_1', SGDClassifier()),
                             ('unit_2', SGDClassifier()),
                             ('unit_3', SGDClassifier()),
                             ('unit_4', SGDClassifier()),
                             ('unit_5', SGDClassifier()),
                             ('unit_6', SGDClassifier()),
                             ('unit_7', SGDClassifier()),
                             ('unit_8', SGDClassifier()),
                             ('unit_9', SGDClassifier()),
                             ('unit_10', SGDClassifier()),
                             ('unit_11', SGDClassifier()),
                             ('unit_12', SGDClassifier()),
                             ('unit_13', SGDClassifier()),
                             ('unit_14', SGDClassifier()),
                             ('unit_15', SGDClassifier()),
                             ('unit_16', SGDClassifier()),
                             ('unit_17', SGDClassifier()),
                             ('unit_18', SGDClassifier()),
                             ('unit_19', SGDClassifier())])

In [37]:
nn = [(f"unit_{i}", VotingClassifier(units)) for i in range(5)]

In [38]:
nn

[('unit_0',
  VotingClassifier(estimators=[('unit_0', SGDClassifier()),
                               ('unit_1', SGDClassifier()),
                               ('unit_2', SGDClassifier()),
                               ('unit_3', SGDClassifier()),
                               ('unit_4', SGDClassifier()),
                               ('unit_5', SGDClassifier()),
                               ('unit_6', SGDClassifier()),
                               ('unit_7', SGDClassifier()),
                               ('unit_8', SGDClassifier()),
                               ('unit_9', SGDClassifier()),
                               ('unit_10', SGDClassifier()),
                               ('unit_11', SGDClassifier()),
                               ('unit_12', SGDClassifier()),
                               ('unit_13', SGDClassifier()),
                               ('unit_14', SGDClassifier()),
                               ('unit_15', SGDClassifier()),
                      

In [51]:
real_nn = MLPClassifier(hidden_layer_sizes = (3, 8, 15), max_iter = 5000) # размерите на скритите слоеве

In [43]:
real_nn

MLPClassifier(hidden_layer_sizes=(3, 8, 15))

In [52]:
digits = load_digits()

In [53]:
digits_attributes, digits_classes = digits["data"], digits["target"]

In [54]:
real_nn.fit(digits_attributes, digits_classes)

MLPClassifier(hidden_layer_sizes=(3, 8, 15), max_iter=5000)

In [57]:
type(real_nn.coefs_)  # this is a python list because they are different as sizes

list

In [61]:
len(real_nn.coefs_)  # this is the count layers like the 4-th is output

4

In [59]:
real_nn.coefs_[0].shape

(64, 3)

64 на 3 е тази матрица, която описва теглото на всички възможни данни към всички възможни елементи в първия слой. към всеки от 3-те слоя влиза по един byias term.

In [60]:
real_nn.intercepts_

[array([ 0.51057141,  0.38783442, -0.27208709]),
 array([ 0.84155347, -0.47865836, -0.38884769, -0.69598815, -1.38251527,
         0.88814576,  0.86306201,  1.59093544]),
 array([-0.28903203, -0.51082205,  1.03352801, -0.27258147,  0.21675445,
         1.50125449, -0.0039616 ,  0.16238611, -0.49827227,  1.64325302,
        -0.36495826, -1.52587453, -0.5083233 , -0.41249886,  0.50526931]),
 array([-0.17826592,  0.78228558, -0.29075592, -0.01322816, -0.23640719,
        -0.71825506, -0.68253109, -0.2237784 ,  0.70503086, -0.01692452])]

Когато имплементираме невронна мрежа векторизацията в numpy и матриците са много важни. Трябва да бъде бързо. Препоръчително е да не се използва OOP, защото в бавно.

In [64]:
real_nn.coefs_[2].shape  # броя входни към броя изходни

(8, 15)

In [66]:
real_nn.predict(digits_attributes[:20])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 2])

In [68]:
real_nn.predict_proba(digits_attributes[:20])  # за всеки един запис всичките вероятности

array([[8.57246881e-01, 6.32009527e-04, 8.65391010e-22, 3.32151172e-09,
        4.03824195e-04, 1.41441112e-01, 1.20246552e-06, 3.23504991e-08,
        2.74198933e-04, 7.36065186e-07],
       [6.79337552e-06, 9.02455874e-01, 1.70012931e-05, 1.14321937e-04,
        8.17382203e-04, 5.14508031e-06, 9.01172472e-02, 6.31836904e-07,
        6.46560329e-03, 2.73997822e-12],
       [1.50558455e-10, 1.04798566e-04, 9.99410610e-01, 2.20730444e-06,
        2.71669812e-10, 2.73276688e-10, 1.14361353e-09, 1.97041993e-13,
        1.38573467e-04, 3.43808659e-04],
       [3.57873607e-08, 5.06876040e-02, 1.89861299e-03, 9.41681179e-01,
        7.86728137e-07, 2.86168126e-08, 5.08056047e-08, 5.66840403e-05,
        3.02292096e-03, 2.65209719e-03],
       [1.39437621e-07, 1.75262386e-05, 2.90696611e-25, 5.29164022e-13,
        9.99683652e-01, 4.79487265e-06, 2.93886378e-04, 1.27056517e-11,
        1.02352040e-09, 1.01969340e-31],
       [9.92739544e-02, 4.01851833e-02, 2.95526251e-09, 3.82122528e-04,
   

$L_{1} = h(Xw^1)$  

Първия слой взима данните $X$, умножава ги по теглата на първия слой $w^1$ и цялото това нещо го преминава през активационната функция $h$ . Подаваме резултата на втория слой, след това резултата от цялото това нещо на третия слой и т.н.

$L{3}(L{2}(L{1}(X)))$

$L{2} = h(h(Xw^1)w^2)$

Правилото е композиция на сложна функция. Производната на сложна функция представлява производната на външната функция умножена по вътрешната.

Една __Логистична регресия__ представлява сигмоид функция от линейната регресия вътре в нея.

Много графи заедно правят един слой, много на брой такива слоеве правят невронна мрежа.

Сайт за ML задачи като Judge - code chalenges:
https://www.deep-ml.com/

keras е библиотека, която позволява да се правят бързо стандартни невронни мрежи.